import type { APIRoute } from "astro";

import {
  SITE_DESCRIPTION,
  SITE_LANG,
  SITE_TITLE,
  THEME_COLOR,
} from "../consts";

/**
 * Web app manifest, served as a route rather than a static file in public/ so
 * the name, language and theme colour come from src/consts.ts instead of being
 * duplicated and drifting.
 *
 * Icons are generated by `pnpm favicons` (scripts/generate-favicons.mjs).
 */
export const GET: APIRoute = () =>
  new Response(
    JSON.stringify(
      {
        name: SITE_TITLE,
        short_name: "Lofoten jazz",
        description: SITE_DESCRIPTION,
        lang: SITE_LANG,
        dir: "ltr",
        start_url: "/",
        scope: "/",
        id: "/",
        display: "standalone",
        orientation: "portrait",
        theme_color: THEME_COLOR,
        // White, because the logo is knocked out of a transparent background
        // and is drawn onto white everywhere else.
        background_color: "#ffffff",
        categories: ["music", "entertainment", "events"],
        icons: [
          { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
          {
            // "maskable" lets Android crop to its own shape without clipping
            // the artwork — this variant keeps the logo inside the safe zone.
            src: "/icon-maskable-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
      null,
      2,
    ),
    {
      headers: {
        // The spec's type; some tooling still sniffs for application/json.
        "Content-Type": "application/manifest+json; charset=utf-8",
      },
    },
  );
